import "./About.scss";

export default function About() {
  return (
    <>
      <section className="about">
        <h3>Text Generated by AI.</h3>
        <p className="about__description">
          I am a web developer in the making. With a keen eye for design and a
          passion for crafting engaging digital experiences, I am dedicated to
          mastering the art of coding and design principles. My journey into the
          world of web development is fueled by a desire to blend creativity
          with technical expertise, pushing the boundaries of what is possible
          on the digital frontier.
        </p>
        <p className="about__description paragraph-margin">
          As I immerse myself in the latest technologies and best practices, I
          am constantly seeking opportunities to expand my knowledge and refine
          my craft. Whether it's experimenting with new frameworks or perfecting
          responsive design techniques, I approach each project with enthusiasm
          and a commitment to excellence.
        </p>
        <p className="about__description">
          Join me on this exciting journey as I strive to transform ideas into
          interactive, visually stunning websites that leave a lasting
          impression. Together, let's shape the future of the web, one line of
          code at a time.
        </p>
      </section>
    </>
  );
}
